### ISSUE TITLE
完美程度疑问

### ISSUE THREAD

**Issue by ddzlcvip** [asinggih/xps9360-opencore#2]
如题，有什么不完美的地方吗？10.15.7所有版本都可以用吗？

**Comment by asinggih** [comment]
Hey, had to ask my colleague to understand this. I cannot read Chinese. But I guess you're asking whether the config works with 10.15.7 Catalina? 

I don't seem to be having any issues with mine. Swapped my network card to DW1560. However, I cannot really test the bluetooth (it's working from OS' point of view), but I broke the antennae cable, and it won't connect to any of my bluetooth devices. Airdrop works ok if i remember correctly, though.

**Comment by ddzlcvip** [comment]
I'm so sorry, thank you for your reply. I mean, how perfect is your EFI on MacOS 10.15.7? Your answer seems to have explained that. Thank you again. regards！

**Comment by asinggih** [comment]
You're welcome! Good luck with your build!
